version: "2.0"
services:
  hello-akash:
    image: figureprod/hello-akash:1.0.0
    expose:
      - port: 3000
        as: 80
        to:
          - global: true

profiles:
  compute:
    hello-akash:
      resources:
        cpu:
          units: 1
        memory:
          size: 1Gi
        storage:
          size: 1Gi
  placement:
    hello-akash:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
      pricing:
        hello-akash:
          denom: uakt
          amount: 1000

deployment:
  hello-akash:
    hello-akash:
      profile: hello-akash
      count: 1
